spring:
  application:
    name: user-service

keycloak:
  server-url: http://localhost:8080
  realm: payguard
  client-id:  ${CLIENT-ID}
  client-secret: ${CLIENT-SECRET}
  admin:
    username: ${ADMIN-USERNAME}
    password: ${ADMIN-PASSWORD}

resilience4j:
  retry:
    instances:
      keycloak:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - com.maison.mabs.userservice.infrastructure.out.keycloak.exception.KeycloakException

  circuitbreaker:
    instances:
      keycloak:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

server:
  port: 9091